# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(27292A)
$foreground = rgb(C6DEEB)
$color0 = rgb(4C4E4F)
$color1 = rgb(1A2226)
$color2 = rgb(2B546B)
$color3 = rgb(2B546B)
$color4 = rgb(315D76)
$color5 = rgb(3E708A)
$color6 = rgb(457A95)
$color7 = rgb(A5C8DB)
$color8 = rgb(748C99)
$color9 = rgb(232D33)
$color10 = rgb(39708F)
$color11 = rgb(39708F)
$color12 = rgb(427C9D)
$color13 = rgb(5395B8)
$color14 = rgb(5CA2C7)
$color15 = rgb(A5C8DB)
