# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(000011)
$foreground = rgb(E3EFFA)
$color0 = rgb(000011)
$color1 = rgb(142450)
$color2 = rgb(265EA1)
$color3 = rgb(265EA1)
$color4 = rgb(265EA1)
$color5 = rgb(829DB5)
$color6 = rgb(839DB5)
$color7 = rgb(CEE0F0)
$color8 = rgb(909DA8)
$color9 = rgb(1B306B)
$color10 = rgb(337ED6)
$color11 = rgb(337ED6)
$color12 = rgb(337ED6)
$color13 = rgb(AED1F1)
$color14 = rgb(AED1F1)
$color15 = rgb(CEE0F0)
