# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(121314)
$foreground = rgb(CEEAD9)
$color0 = rgb(3A3A3B)
$color1 = rgb(101618)
$color2 = rgb(283F34)
$color3 = rgb(373E4B)
$color4 = rgb(3F6850)
$color5 = rgb(A8474C)
$color6 = rgb(57926D)
$color7 = rgb(B1D8C0)
$color8 = rgb(7C9786)
$color9 = rgb(151E20)
$color10 = rgb(355545)
$color11 = rgb(495364)
$color12 = rgb(548B6B)
$color13 = rgb(E05F65)
$color14 = rgb(74C291)
$color15 = rgb(B1D8C0)
